### ISSUE TITLE
Global translations

### ISSUE THREAD

**Issue by innocenzi** [innocenzi/laravel-vue-lang#8]
@rvbz In your pull request (which I thank you for), you added support for "root-level" translations with a `_global` key. (https://github.com/innocenzi/laravel-vue-lang/pull/7/commits/8b0732b52c672406db3276ab09cfabf2251ae38f) 

Since I didn't understand the use case, I didn't not implement it right away, but I believe you had a reason, so I'd like to understand what is it for, and how do you use it yourself. 

Thanks. :)

**Comment by rvbz** [comment]
@innocenzi so the idea behind this approach is the simplicity of how it works really.
### **Current Folder Structure**
With the current folder structure:
```
-- en
    -- translation.php
-- es
    -- translation.php
```
You have to have 2 files with the same name in the desired locale, which means you have to maintain 2 files every time you need to make a change. Also the fact that it's intended to work only with "Shortkeys" e.g.
```
'user' => "We can't find a user with that email address."
```
USAGE
```
__('translation.user');
```
If you put in consideration a massive application with hundreds of pages, having this `__('translation.user');` in the front-end doesn't really tell you anything, but where to look at for the text.

### Root-level translations
With root label translations all of the previous cons are gone. You would have only one file:
```
-- es.json
```
Which means only 1 file to maintain, only your desired new locale. This approach will also give you an easily detection in front-end as you will have your actual default locale text e.g.
 ```
__("We can't find a user with that email address.");
```
Now, the beauty of this approach is that you have your **default language text** as key, therefore if you don't have the proper translation, the system will return your default language:

No key found with root-level:
 ```
We can't find a user with that email address.
```
No key found with folder-structure (if you don't have it set in neither of your locales):
 ```
translation.user
```
So, that's the idea behind this approach.
### Going back to your package
After all this being said, the job that I did, didn't really get us there, as in order to use `root-level` translations we need to use the `_global.` key, which destroys the simplicity in the front-end:
 ```
__("_global.We can't find a user with that email address.");
```
This will also return the entire sentence if a match is not found on the translation files e.g.
 ```
_global.We can't find a user with that email address.
```
Which as well destroys the entire purpose of the approach. The problem of this is actually coming from the Lang.js package as it needs to have that structure `locale.key`. 

I really love how root-level translations works, so I will do my best to develop something later this week to fix these issues mentioned before. Hope my explanation was understandable and please let me know your thoughts and comments.

Cheers.

**Comment by innocenzi** [comment]
Glad to hear that! 

I'll try to clean up and merge the `___` function with the `__` and do a proper release as soon as I can.
